# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_auto_20160105_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='activate',
            field=models.BooleanField(default=False, help_text=b'activate task (if enabled)'),
        ),
    ]
