# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_auto_20160105_2052'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='explorer.Query'),
        ),
    ]
