# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 04:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20160816_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='query',
        ),
    ]
